services:
  frontend:
    image: ${DOCKER_USERNAME}/procurement-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_API_URL: ${NEXT_PUBLIC_BACKEND_API_URL}
        NEXT_PUBLIC_FRONTEND_URL: ${NEXT_PUBLIC_FRONTEND_URL}
    ports:
      - "3000:3000"
    restart: unless-stopped
